/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_sawada_np2android_SDLActivity */

#ifndef _Included_jp_sawada_np2android_SDLActivity
#define _Included_jp_sawada_np2android_SDLActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_sawada_np2android_SDLActivity
 * Method:    onNativeSoftKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_sawada_np2android_SDLActivity_onNativeSoftKeyDown
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_sawada_np2android_SDLActivity
 * Method:    onNativeSoftKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_sawada_np2android_SDLActivity_onNativeSoftKeyUp
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_sawada_np2android_SDLActivity
 * Method:    onNativeNP2Mouse
 * Signature: (I)V
*/
JNIEXPORT void JNICALL Java_jp_sawada_np2android_SDLActivity_onNativeNP2Mouse
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     jp_sawada_np2android_SDLActivity
 * Method:    onNativeFileDir
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jp_sawada_np2android_SDLActivity_onNativeFileDir
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
